sheet_id: "1PncuqrcU1pmNIHsWNepaJe9IdFDMJnpN82e-Fgdn52Y"
worksheet: "매일 업데이트 되는 전체 임상시험 시트"   # ← 실제 탭 이름
service_account_json: "config/sa.json"

since_sn_buffer: 10
output_dir: "outputs"
wait_seconds: 8
pause: 0.35
max_consecutive_miss: 20
url_templates:
  - "https://trialforme.konect.or.kr/clnctest/view.do?pageNo=&clncTestSn={sn}&relatedSearchKeyword=&searchText=&recruitStartDate=&recruitEndDate=&status="
  - "https://www.koreaclinicaltrials.org/clnctest/view.do?pageNo=&clncTestSn={sn}&relatedSearchKeyword=&searchText=&recruitStartDate=&recruitEndDate=&status="


